# Computing initial stresses on branching fault by okada 


def branching_nodes : 
#  Loading branching nodes. 
   fb=open('branching_nodes','r')
   nbfault=fb.readline()
#  Format :
#  x,y,z,dip
   for i in range(nbfault):
     db=fb.readlines.split()
     xb=float(db[0])
     yb=float(db[1])
     zb=float(db[2])
     dipb=float(90.0)
   
#  Loading main fault nodes.
   fm=open('main_nodes','r')
   nmfault=fm.readline()
#  Format :
#  x,y,z,dip,dx,dw,tau,sigma
   for i in range(nmfault):
     dm   = fb.readlines.split()
     xm   = float(dm[0])
     ym   = float(dm[1])
     zm   = float(dm[2])
     dipm = float(90.0)
     dx   = float(...)
     dw   = fault(dm[5])
     tau_m  = fault(dm[6])
     sigma_m= fault(dm[7])

# compute tau and sigma generated by the main fault on the branch. 
   lam = 4*1e10
   mu  = 4*1e10
   
   
